"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.rankInsignias = exports.ranks = void 0;
exports.ranks = [
    'Private',
    'Private 1st Class',
    'Corporal',
    'Specialist',
    'Sergeant',
    'Staff Sergeant',
    'Sergeant 1st class',
    'Master Sergeant',
    '1st Sergeant',
    'Sergeant Major',
    'Command Sgt Major',
    'Sergeant Major of the Army',
    'Warrant Officer',
    'Chief Warrant Officer',
    '2nd Lieutenant',
    '1st Lieutenant',
    'Captain',
    'Major',
    'Lieutenant Colonel',
    'Colonel',
    'Brigadier General',
    'Major General',
    'Lieutenant General',
    'General',
    'General of the Army',
    'General of the Armies',
    'Commander-in-Chief',
    'Supreme Commander'
];
exports.rankInsignias = {
    'Unknown': "https://i.imgur.com/lAQW7WA.png",
    'Private': "https://i.imgur.com/fYDu35X.png",
    'Private 1st Class': "https://i.imgur.com/PngbcAR.png",
    'Corporal': "https://i.imgur.com/5yL3G5M.png",
    'Specialist': "https://i.imgur.com/WtTzjrz.png",
    'Sergeant': "https://i.imgur.com/Z8dCGT3.png",
    'Staff Sergeant': "https://i.imgur.com/EsJ4e1k.png",
    'Sergeant 1st class': "https://i.imgur.com/LQqDCQQ.png",
    'Master Sergeant': "https://i.imgur.com/NyixXMY.png",
    '1st Sergeant': "https://i.imgur.com/Gci713t.png",
    'Sergeant Major': "https://i.imgur.com/mHD7g0r.png",
    'Command Sgt Major': "https://i.imgur.com/PQd96sy.png",
    'Sergeant Major of the Army': "https://i.imgur.com/XHnde09.png",
    'Warrant Officer': "https://i.imgur.com/Z8l5X5a.png",
    'Chief Warrant Officer': "https://i.imgur.com/CI4OUVr.png",
    '2nd Lieutenant': "https://i.imgur.com/nQueHmL.png",
    '1st Lieutenant': "https://i.imgur.com/EjtHmtj.png",
    'Captain': "https://i.imgur.com/WH0wfy8.png",
    'Major': "https://i.imgur.com/7McfT0J.png",
    'Lieutenant Colonel': "https://i.imgur.com/0DRtoWp.png",
    'Colonel': "https://i.imgur.com/muvXNsK.png",
    'Brigadier General': "https://i.imgur.com/LhzZFxG.png",
    'Major General': "https://i.imgur.com/FrhoSXR.png",
    'Lieutenant General': "https://i.imgur.com/kkc4GsA.png",
    'General': "https://i.imgur.com/6vX6I7U.png",
    'General of the Army': "https://i.imgur.com/RRcpMpc.png",
    'General of the Armies': "https://i.imgur.com/CCHIc2R.png",
    'Commander-in-Chief': "https://i.imgur.com/3ZZWX09.png",
    'Supreme Commander': "https://i.imgur.com/Gs2K28F.png"
};
//# sourceMappingURL=ranks.js.map